### ISSUE TITLE
GridOut object has no attribute X

### ISSUE THREAD

**Issue by iffy** [twisted/txmongo#40]
It seems like GridFS.get and .put don't work at all...

```python
from twisted.internet import reactor
import txmongo
from txmongo.gridfs import GridFS

d = txmongo.MongoConnectionPool()

def gotDB(db):
    files = GridFS(db.fs, collection='foo')
    print files
    return files


def gotFiles(files):
    obj_id = files.put('some contents', filename='foo', content_type='image/png')
    print 'saved', repr(obj_id)
    obj = files.get(str(obj_id))
    print 'got', repr(obj)
    print dir(obj)
    print obj.read()
    print obj.name
    print obj.content_type

d.addCallback(gotDB)
d.addCallback(gotFiles)

reactor.run()
```

gives me this:

```
<txmongo._gridfs.GridFS object at 0x12885d0>
saved ObjectId('4fe84a9bf648c2b4df000001')
got 4fe84a9bf648c2b4df000001
['_GridOut__buffer', '_GridOut__chunks', '_GridOut__current_chunk', '_GridOut__position', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__iter__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_file', '_id', 'aliases', 'chunk_size', 'close', 'content_type', 'length', 'md5', 'metadata', 'name', 'read', 'seek', 'tell', 'upload_date']
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/Volumes/FatMan/home/matt/venvs/things/lib/python2.6/site-packages/Twisted-12.1.0-py2.6-macosx-10.3-fat.egg/twisted/internet/defer.py", line 464, in _startRunCallbacks
    self._runCallbacks()
  File "/Volumes/FatMan/home/matt/venvs/things/lib/python2.6/site-packages/Twisted-12.1.0-py2.6-macosx-10.3-fat.egg/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "badmongo.py", line 19, in gotFiles
    print obj.read()
  File "/Volumes/FatMan/home/matt/venvs/things/lib/python2.6/site-packages/Twisted-12.1.0-py2.6-macosx-10.3-fat.egg/twisted/internet/defer.py", line 1187, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/Volumes/FatMan/home/matt/venvs/things/lib/python2.6/site-packages/Twisted-12.1.0-py2.6-macosx-10.3-fat.egg/twisted/internet/defer.py", line 1045, in _inlineCallbacks
    result = g.send(result)
  File "build/bdist.macosx-10.3-fat/egg/txmongo/_gridfs/grid_file.py", line 345, in read
    
  File "build/bdist.macosx-10.3-fat/egg/txmongo/_gridfs/grid_file.py", line 331, in __getattr__
    
exceptions.AttributeError: GridOut object has no attribute 'length'
<Deferred at 0x128aee0 current result: <twisted.python.failure.Failure <type 'exceptions.AttributeError'>>>
```

I think it's because `GridFS.put` returns `grid_file._id`, and `GridFS.get` takes a `file_id`, but uses that id as if it were a document in this line:
```python
return GridOut(self.__collection, file_id)
```

**Comment by psi29a** [comment]
@iffy You still interested in making that patch? :)

**Comment by iffy** [comment]
@psi29a Probably not :(  We ended up not using Mongo, so it would be far afield of what I'm doing now.

**Comment by IlyaSkriblovsky** [comment]
`GridFS.put()` seems to be working now. May we close this issue?

**Comment by psi29a** [comment]
I think we can close this, if someone tests and isn't happy... they can post here and we can re-open it.
